add MMM-AuthenticatedUptimeKuma MagicMirror² 3rd party addon
louislam/uptime-kuma-wiki pull request #104
Opened 2024-12-02 19:32 UTC by totoluto

2025-01-21 09:15 UTC, IV-R requested changes
Conținutul fișierului (README.md):

# Uptime Kuma Wiki Contribution

## Overview
This document serves as a guideline for contributing to the **Uptime Kuma Wiki**. Please ensure all new documentation aligns with the project's standards and provides clear, concise information.

## Sections to be Added

1. **Installation Steps**
    - Add details about installation on different operating systems.
    - Provide examples for Docker, Kubernetes, and manual installations.

2. **Configuration Guide**
    - Explanation of environment variables.
    - Sample configuration files.
    - Common troubleshooting tips.

3. **Monitoring Setup**
    - Step-by-step guides for setting up monitoring.
    - Integration with third-party tools like Prometheus and Grafana.

4. **FAQ Section**
    - Address common user questions and issues.
    - Link to existing GitHub issues for reference.

## Contribution Guidelines

1. Ensure proper Markdown formatting.
2. Follow the style guide outlined in the main project.
3. Submit pull requests with detailed descriptions.
4. Review existing documentation before adding new content.

## Contact

For further questions or suggestions, please reach out via GitHub issues or discussions.

2025-01-21 12:25 UTC, CommanderStorm commented
@IV-R WTF??

@totoluto Please ignore their review

2025-02-02 11:19 UTC, totoluto commented
@CommanderStorm What did i miss? I don't see any review?

2025-02-02 11:49 UTC, CommanderStorm commented
You did miss nothing of note.
An LLM made an hallucinated comment. 🤷‍♂️

2025-05-06 12:40 UTC, merged