Update Reverse-Proxy.md
louislam/uptime-kuma-wiki pull request #81
Opened 2024-02-01 20:54 UTC by ajnadox

update Caddy installation

2024-02-01 22:33 UTC, CommanderStorm requested changes

2024-02-01 22:33 UTC, CommanderStorm commented on Reverse-Proxy.md
> +edit nano /etc/caddy/Caddyfile, Delete everything in the file and replace it with (change to your domain):
See above

```suggestion
```

2024-02-01 22:33 UTC, CommanderStorm commented on Reverse-Proxy.md
> +Install Caddy server
What is happening right here?
I think you are trying to install caddy here => linking their installation guide is the appropriate way to do that

We cannot maintain a way to install caddy in the wiki.

```suggestion
After [instally caddy](https://caddyserver.com/docs/install), edit your `Caddyfile` (by default at `/etc/caddy/Caddyfile`) and add the following:
```

2024-02-01 22:33 UTC, CommanderStorm commented on Reverse-Proxy.md
> +```
Caddy supports more than just the linux instation instructions.
Please reflect this in the installation guide or link to the appropriate docs instead

2024-02-01 22:33 UTC, CommanderStorm commented on Reverse-Proxy.md
> +You should now be able to point a browser to https://subdomain.domain.com/ and see your Uptime Kuma site
```suggestion
Uptime Kuma is now avaliable at https://subdomain.domain.com/
```

2024-02-02 03:03 UTC, louislam commented
Same reason as #80

2024-02-02 03:03 UTC, closed without merging